### ISSUE TITLE
Request: full name (including folder path) of Glamourer presets in selection UI

### ISSUE THREAD

**Issue by PrincessRTFM** [NightmareXIV/DynamicBridge#1]
I don't know how others use it, but I organise my Glamourer presets by category, then - for full customisations - by name, then within those folders I name the preset itself by a short description. This leaves me having several presets with the same name but different paths, especially since I usually save one called `_BASE` for people so that I can load their look and then fiddle with clothing after. The result is that I've got, eg, `People/My Name/Casual`, and then also `People/My Friend/Casual`, `People/Other Friend/Casual`, etc. The problem is that when selecting a Glamourer preset to apply, only the name is displayed, so I have no idea _which_ `Casual` preset is which.

If the full name of the Glamourer preset could be displayed, it would solve this problem perfectly.

**Comment by AsunaTsuki** [comment]
Thank you for the suggestion, will see what we can do

**Comment by PrincessRTFM** [comment]
Addendum: I tried to temporarily rename the Glamourer preset I wanted to use, thinking that might work since Glamourer clearly uses UUIDs so I could probably rename it back once I selected it, but Dynamic Bridge's list of presets didn't update with the new name. I don't know whose side is responsible for that, but I thought I'd mention it as well, since it seemed like it might be a bug. I can open a new issue for that if it is.

**Comment by Limiana** [comment]
> Addendum: I tried to temporarily rename the Glamourer preset I wanted to use, thinking that might work since Glamourer clearly uses UUIDs so I could probably rename it back once I selected it, but Dynamic Bridge's list of presets didn't update with the new name. I don't know whose side is responsible for that, but I thought I'd mention it as well, since it seemed like it might be a bug. I can open a new issue for that if it is.

Hello! Refreshing issue will be addressed in next update. While Glamourer does use GUID, DynamicBridge selects presets by name. I'll think of what can be done here and in which way.

**Comment by Limiana** [comment]
Full path display can be now activated in settings. For customize+ the similar feature will be implemented at a later date
