### ISSUE TITLE
[Bug] Reopen ticket #7 JP/CN language issue v1.0.4.5

### ISSUE THREAD

**Issue by AngelFireOmega** [NightmareXIV/DynamicBridge#10]
https://github.com/NightmareXIV/DynamicBridge/issues/7
Test failed on v1.0.4.5
Log file attached.
[log_1.0.4.5.zip](https://github.com/NightmareXIV/DynamicBridge/files/14580251/log_1.0.4.5.zip)

Note: When I tried to download the log file I uploaded the 404 error occured. Let me know if you need me to upload it again.

**Comment by Limiana** [comment]
Sorry, seems like old version of the library sneaked up into the build. Should be fixed now, please test it

**Comment by AngelFireOmega** [comment]
Issue fixed and tested with v1.0.4.7

I also checked out the repository and reviewed the commit history.
All I can say is combining the sveral implimentation into one commit not a good idea.

**Comment by Limiana** [comment]
Thank you for testing!
I would like to properly commit and comment the entire code of course, but it all boils down to having limited time and often it's a choice between function, design, clean commits and documentation. Rest assured - once I'll be able to dedicate more time to the plugins - all the aspects will receive proper treatment and I myself look forward to it too!
