### ISSUE TITLE
Unable to apply Advanced Dyes options from a Glamourer Design

### ISSUE THREAD

**Issue by MB-Solent** [NightmareXIV/DynamicBridge#12]
Dynamic Bridge seems unable to apply Advances Dyes (Glamourer Colourset Changes).

I've tested this using a Preset, both using a Layered Design containing the glamourer design and just selecting the Glamourer design in the Preset Dropdown.

I've tested this using 2 different modded outfits, neither having advanced dyes applied properly.

The test outfit:
Applied via Dynamic Bridge Preset
![image](https://github.com/NightmareXIV/DynamicBridge/assets/114576225/31ebe51b-ed54-41dd-9789-98ffde468573)

Applied directly from glamourer
![image](https://github.com/NightmareXIV/DynamicBridge/assets/114576225/bb7b18c8-5535-4b27-b026-2b8c8acc91d2)

**Comment by viewtyjoe** [comment]
Otter thinks the IPC issue may be resolved with 1.2.3.2 which just released. I will do some testing tonight.

**Comment by viewtyjoe** [comment]
Can confirm Glamourer 1.2.3.2 has resolved the bug, designs with advanced dye on gear are applying correctly instead of for one frame.

**Comment by Limiana** [comment]
Thanks for reporting!
