### ISSUE TITLE
Feature: Player based rules

### ISSUE THREAD

**Issue by AsunaTsuki** [NightmareXIV/DynamicBridge#13]
Rules that are player character based
such as: 
-if [player name@world] is in the same {instance} as self, rule is applied
-if ONLY [player name@world] is in the same {instance} as self, AND NO OTHER PCS, then rule is applied

**Comment by PrincessRTFM** [comment]
Not really viable outside of very small instance zones like housing, since players more than a certain distance away aren't known to the client.
