### ISSUE TITLE
New Glamourer/Penumbra update today causes IPC error

### ISSUE THREAD

**Issue by shadowking1443** [NightmareXIV/DynamicBridge#17]
Hi team!

Today after login, both Glamourer and Penumbra updated with some significant changes. This appears to have caused an IPC error, listed below, when attempting to apply an outfit from Dynamic Bridge. This prevents the outfit from apply at all.

"IPC method Glamourer.RevertCharacter was not registered yet"

**Comment by Limiana** [comment]
Hey, should be good with 1.0.5.9
