### ISSUE TITLE
Glamourer folder picker not showing actual folder names

### ISSUE THREAD

**Issue by AsunaTsuki** [NightmareXIV/DynamicBridge#19]
![image](https://github.com/NightmareXIV/DynamicBridge/assets/99369560/8b9ee0ef-1988-4250-84f8-7216c301f0df)

![image](https://github.com/NightmareXIV/DynamicBridge/assets/99369560/4788122a-097c-4ddb-b4eb-b5c6b76d5657)

If you have sub folders inside of folders, all the folders in the picker shows the top folder name. see the screenshots

**Comment by Limiana** [comment]
Issue should be fixed
