### ISSUE TITLE
Duty Zone Group doesn't work

### ISSUE THREAD

**Issue by Styx-Blackwell** [NightmareXIV/DynamicBridge#3]
Hiya, when being in /entering a Duty the presets that should apply unfortunately don't. I have not found a workaround
![image](https://github.com/NightmareXIV/DynamicBridge/assets/95082748/b9aedda8-61e6-4953-8dd2-e5c810b1babd)

**Comment by Limiana** [comment]
Hello!
Please update to the latest version and try again. If it doesn't helps, please send another screenshot and a log from log tab.

**Comment by Limiana** [comment]
The issue was identified and will be fixed in next version

**Comment by Styx-Blackwell** [comment]
Thank you!
I look forward to using this plugin extensively <3 It's awesome and I have been wanting something like it for a long time

**Comment by Limiana** [comment]
This issue should be fixed now
