### ISSUE TITLE
Customize+ recent update seems unlinking the existing profiles

### ISSUE THREAD

**Issue by xerxes-yelnos** [NightmareXIV/DynamicBridge#4]
Hello!

I am really glad to have found this useful plugin recently that I use mostly to change the size of my character with Customize+.

But since today's recent update from Customize+, it seems that DynamicBridge cannot find my existing Customize+ profiles anymore and when I look up my Preset tab under the field of Customize+, all the names are in red now and when I untick the name, my Customize+ profile suddenly disappear from the DynamicBridge, which makes it not able to read the Customize+ data anymore.

Is this problem only happening on my side?
I already restarted and reinstall the DynamicBridge but it's still not working...

I do hope that it'll be fixed soon!!

![image](https://github.com/NightmareXIV/DynamicBridge/assets/132729006/462caf8b-916a-4238-b5ed-7ed047642c66)

**Comment by Limiana** [comment]
Hello!
When dependency plugins update, sometimes some things may stop working. I will fix it shortly

**Comment by Limiana** [comment]
@xerxes-yelnos everything should be working after update, please check it and let me know the result

**Comment by xerxes-yelnos** [comment]
> @xerxes-yelnos everything should be working after update, please check it and let me know the result

it worked now!

thank you so much and keep up the good work Limiana!!!
